name: describe_relations
data:
  file: data/bbox_pairs_100.tsv
  input:
    image: url
  output:
    result: str
interface:
  prompt: Read the instructions first. Then concisely describe the relationship between the two outlined elements.
project:
  setup:
    public_name: Describe relations between diagram elements
    public_description: Look at the diagrams and describe the relationship between the outlined elements.
  instructions: instructions/instructions.html
pool:
  estimated_time_per_suite: 240
  setup:
    private_name: Describe relations
    reward_per_assignment: 0.8
    assignment_max_duration_seconds: 900
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 5
    default_overlap_for_new_task_suites: 5
  mixer:
    real_tasks_count: 4
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    languages:
    - EN
  speed_quality_balance:
    top_percentage_by_quality: 10
quality_control:
  fast_responses:
    history_size: 5
    count: 2
    threshold: 10
    ban_duration: 7
    ban_units: DAYS
  captcha:
    frequency: MEDIUM
    success_rate: 80
    ban_duration: 7
    ban_units: DAYS
  redo_banned: True
