name: describe_relations
data:
  file: data/ai2d_bboxes.tsv
  input:
    image: url
    outlines: json
  output:
    result: str
interface:
  prompt: Read the instructions first. Then describe the relation between the two outlined elements.
project:
  setup:
    public_name: Describe relations
    public_description: Look at the diagrams and describe the relation between the outlined elements.
  instructions: instructions/instructions.html
training:
pool:
  estimated_time_per_suite: 60
  setup:
    private_name: Describe relations
    reward_per_assignment: 0.2
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 2
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    languages:
    - EN
    client_type:
    - TOLOKA_APP
    - BROWSER